### ISSUE TITLE
Spinning circle when call MSL App website

### ISSUE THREAD

**Issue by Just4Link** [Steiger04/ioBroker.milight-smart-light#48] opened 2021-05-16 09:44 UTC
I set up the MSL app with the default settings like in the manual.

When i try to connect to the website with ipadress:4400 i only see a spinning circle and
it wont go further. Try'd another port too, nothing changed.

Socket port is 8082 with the integrated option. I try'd a separate iosocket instancewith 8084 too, but same behavior.

I try it on pc using chrome and with my smartphone using firefox.

**Comment by Steiger04** [comment] 2021-05-17 17:26
This is a problem with the socket. You have to create a separate socketio instance (adapter socket.io) and not use the internal instance of the web adapter. Very important: used version **3.0.12**. Something has been changed in the current socket.io adapter (analogous to the current web adapter), which leads to the errors. I'll patch that in my adapter soon.

**Comment by Just4Link** [comment] 2021-05-17 17:36
ok then i wait for the update instead of downgrading the socket adapter. Thanks for your answer :)

**Comment by Steiger04** [comment] 2021-05-19 14:35
The problem is fixed with v1.2.1.

**Closed as completed** 2021-05-21 14:46 UTC
